package ar.edu.unju.virtual.model.domain;
// Generated Jan 6, 2019 1:00:54 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {
  public static final String HABILITADO = "HABILITADO";
  public static final String INHABILITADO = "INHABILITADO";
  
  private long id;
  private Cliente cliente;
  private long dni;
  private String nombreUsuario;
  private String clave;
  private String nombre;
  private String domicilio;
  private String email;
  private String estado;
  private Set cuentas = new HashSet(0);
  private Set clientes = new HashSet(0);

  public Cliente() {}
  
  public Cliente(String nombre, long dni, String domicilio, String email, String nombreUsuario, String clave,
       String estado) {
    this.nombre = nombre;
    this.dni = dni;
    this.domicilio = domicilio;
    this.email = email;
    this.nombreUsuario = nombreUsuario;
    this.clave = clave;
    this.estado = estado;
  }

  public Cliente(Cliente titular, String nombre, long dni, String domicilio, String email, String nombreUsuario, String clave,
      String estado) {       
    this.cliente = titular;
    this.nombre = nombre;
    this.dni = dni;
    this.domicilio = domicilio;
    this.email = email;
    this.nombreUsuario = nombreUsuario;
    this.clave = clave;
    this.estado = estado;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Cliente getCliente() {
    return this.cliente;
  }

  public void setCliente(Cliente cliente) {
    this.cliente = cliente;
  }

  public long getDni() {
    return this.dni;
  }

  public void setDni(long dni) {
    this.dni = dni;
  }

  public String getNombreUsuario() {
    return this.nombreUsuario;
  }

  public void setNombreUsuario(String nombreUsuario) {
    this.nombreUsuario = nombreUsuario;
  }

  public String getClave() {
    return this.clave;
  }

  public void setClave(String clave) {
    this.clave = clave;
  }

  public String getNombre() {
    return this.nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public String getDomicilio() {
    return this.domicilio;
  }

  public void setDomicilio(String domicilio) {
    this.domicilio = domicilio;
  }

  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getEstado() {
    return this.estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public Set getCuentas() {
    return this.cuentas;
  }

  public void setCuentas(Set cuentas) {
    this.cuentas = cuentas;
  }

  public Set getClientes() {
    return this.clientes;
  }

  public void setClientes(Set clientes) {
    this.clientes = clientes;
  }

}
