package ar.edu.unju.virtual.model.domain;
// Generated Jan 6, 2019 1:00:54 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable {

  private long id;
  private Cliente cliente;
  private String numero;
  private Date fechaIngreso;
  private Float saldoActual;
  private String estado;
  private Long limiteExtraccion;
  private Set movimientos = new HashSet(0);

  public Cuenta() {
  }

  public Cuenta(long id, Cliente cliente) {
    this.id = id;
    this.cliente = cliente;
  }

  public Cuenta(long id, Cliente cliente, String numero, Date fechaIngreso, Float saldoActual, String estado,
      Long limiteExtraccion, Set movimientos) {
    this.id = id;
    this.cliente = cliente;
    this.numero = numero;
    this.fechaIngreso = fechaIngreso;
    this.saldoActual = saldoActual;
    this.estado = estado;
    this.limiteExtraccion = limiteExtraccion;
    this.movimientos = movimientos;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Cliente getCliente() {
    return this.cliente;
  }

  public void setCliente(Cliente cliente) {
    this.cliente = cliente;
  }

  public String getNumero() {
    return this.numero;
  }

  public void setNumero(String numero) {
    this.numero = numero;
  }

  public Date getFechaIngreso() {
    return this.fechaIngreso;
  }

  public void setFechaIngreso(Date fechaIngreso) {
    this.fechaIngreso = fechaIngreso;
  }

  public Float getSaldoActual() {
    return this.saldoActual;
  }

  public void setSaldoActual(Float saldoActual) {
    this.saldoActual = saldoActual;
  }

  public String getEstado() {
    return this.estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public Long getLimiteExtraccion() {
    return this.limiteExtraccion;
  }

  public void setLimiteExtraccion(Long limiteExtraccion) {
    this.limiteExtraccion = limiteExtraccion;
  }

  public Set getMovimientos() {
    return this.movimientos;
  }

  public void setMovimientos(Set movimientos) {
    this.movimientos = movimientos;
  }

}
