package ar.edu.unju.virtual.model.domain;
// Generated Jan 6, 2019 1:00:54 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento implements java.io.Serializable {

  private long id;
  private Cuenta cuenta;
  private Date fecha;
  private Float debito;
  private Float credito;
  private Float saldo;  
  private Cliente cliente;

  public Movimiento() {
  }

  public Movimiento(long id, Cuenta cuenta, Date fecha, Cliente cliente) {
    this.id = id;
    this.cuenta = cuenta;
    this.fecha = fecha;
    this.cliente = cliente;
  }

  public Movimiento(long id, Cuenta cuenta, Date fecha, Float debito, Float credito, Float saldo, Cliente cliente) {
    this.id = id;
    this.cuenta = cuenta;
    this.fecha = fecha;
    this.debito = debito;
    this.credito = credito;
    this.saldo = saldo;
    this.cliente = cliente;
  }

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Cuenta getCuenta() {
    return this.cuenta;
  }

  public void setCuenta(Cuenta cuenta) {
    this.cuenta = cuenta;
  }

  public Date getFecha() {
    return this.fecha;
  }

  public void setFecha(Date fecha) {
    this.fecha = fecha;
  }

  public Float getDebito() {
    return this.debito;
  }

  public void setDebito(Float debito) {
    this.debito = debito;
  }

  public Float getCredito() {
    return this.credito;
  }

  public void setCredito(Float credito) {
    this.credito = credito;
  }

  public Float getSaldo() {
    return this.saldo;
  }

  public void setSaldo(Float saldo) {
    this.saldo = saldo;
  }  

  public Cliente getCliente() {
    return cliente;
  }

  public void setCliente(Cliente cliente) {
    this.cliente = cliente;
  }
  
}
